-- bales_production_logs: one row per Bales shift per day, written LIVE as
-- the shift runs by components/BalesForm.tsx (insert on first cycle submit,
-- update on every submit after), mirroring production_logs for Press.
--
-- No table_line_output_yields / good-reject split (Bales has no 4-table
-- concept) -- total_bales_produced / total_faulty_bales / total_run_time_minutes
-- are the Bales-appropriate rollups instead. "Total Mats Produced" on the
-- paper footer is treated as a template leftover from a Press-line sheet;
-- the correct semantic here is total_bales_produced.
--
-- Unlike production_logs_dedupe.sql, this table starts empty, so the unique
-- index is created directly -- no separate inspect/cleanup pass is needed.
--
-- Not applied via a migration tool -- run this manually in the Supabase SQL
-- editor (same convention as shift_config.sql / production_logs_rls.sql /
-- production_logs_dedupe.sql).

CREATE TABLE IF NOT EXISTS public.bales_production_logs (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                     TEXT NOT NULL,        -- YYYY-MM-DD, Perth
  operator_shift           TEXT,                 -- "${operator} (${shift})"
  cycles                   JSONB DEFAULT '[]'::jsonb,
  total_bales_produced     INTEGER,
  total_faulty_bales       INTEGER,
  total_run_time_minutes   INTEGER,
  main_issues_faults       TEXT,                 -- shift-level free-text summary
  updated_at               TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.bales_production_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "bales_production_logs read" ON public.bales_production_logs
  FOR SELECT USING (true);

CREATE POLICY "bales_production_logs insert" ON public.bales_production_logs
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "bales_production_logs update" ON public.bales_production_logs
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- One row per (date, shift group), matching production_logs_one_per_shift_day.
-- Both lower() and position() are IMMUTABLE, so this expression is indexable.
--
-- components/BalesForm.tsx must handle the resulting unique violation
-- (SQLSTATE 23505) exactly like PressForm.tsx: re-resolve the shift's row
-- and update it instead of erroring.
CREATE UNIQUE INDEX IF NOT EXISTS bales_production_logs_one_per_shift_day
  ON public.bales_production_logs (
    date,
    (position('night' in lower(operator_shift)) > 0)
  );

-- Note: no total_downtime column. Like production_logs, downtime is a
-- live-log-derived display metric computed in BalesProductionTable.tsx, not
-- an archived column (mirrors Press's precedent exactly).
