-- bales_live_log: one row per Bales cycle (bag-run) within the current
-- shift, mirroring live_log's role for Press. Unlike live_log this table has
-- no pre-existing dashboard-created shape, so this is a full CREATE TABLE.
--
-- end_time is NOT a separate operator-entered field on the paper form -- it
-- is computed by components/BalesForm.tsx as start_time + run_time_minutes
-- and stored so app/BalesProductionTable.tsx can compute the Total Downtime
-- "idle gap" metric (see that file's comment) without re-deriving it.
--
-- mesh_type is snapshotted per row (same principle as live_log.run_time_minutes,
-- see live_log_add_run_time.sql) so a later change to the shift-wide mesh
-- type doesn't retroactively alter historic rows.
--
-- Not applied via a migration tool -- run this manually in the Supabase SQL
-- editor (same convention as shift_config.sql).

CREATE TABLE IF NOT EXISTS public.bales_live_log (
  bales_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id            INTEGER NOT NULL DEFAULT 1,
  cycle_number        INTEGER NOT NULL,
  start_time          TIMESTAMPTZ,
  end_time            TIMESTAMPTZ,
  run_time_minutes    INTEGER,
  bales_produced      INTEGER,
  bale_type           TEXT,
  faulty_bales_count  INTEGER DEFAULT 0,
  mesh_type           TEXT,
  notes               TEXT,
  updated_at          TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.bales_live_log ENABLE ROW LEVEL SECURITY;

-- Anyone (incl. the boss, not logged in) can READ the live cycle grid.
CREATE POLICY "bales_live_log read" ON public.bales_live_log
  FOR SELECT USING (true);

-- Only logged-in operators can WRITE.
CREATE POLICY "bales_live_log insert" ON public.bales_live_log
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "bales_live_log update" ON public.bales_live_log
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Deliberately NO DELETE policy -- same footgun/design as live_log (see
-- reset_shift_log.txt's comment). Clearing only happens through the
-- SECURITY DEFINER reset_bales_shift_log RPC (reset_bales_shift_log.txt).

ALTER PUBLICATION supabase_realtime ADD TABLE public.bales_live_log;
