-- bales_bag_changes: one row per East/West bag-change event, logged via a
-- dedicated "Log Bag Change" dialog in components/BalesForm.tsx (not part of
-- the per-cycle row -- matches the paper's occasional-use "Bag # and weight"
-- cell pattern). Read + realtime-subscribed by app/BalesProductionTable.tsx
-- for its bag-changes mini-log.
--
-- Immutable event log (like shift_messages.sql) -- no UPDATE policy, since a
-- bag change is a fact recorded once, not an editable draft.
--
-- Not applied via a migration tool -- run this manually in the Supabase SQL
-- editor (same convention as shift_messages.sql).

CREATE TABLE IF NOT EXISTS public.bales_bag_changes (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id         INTEGER NOT NULL DEFAULT 1,
  side             TEXT NOT NULL,          -- 'east' | 'west'
  sequence_number  INTEGER NOT NULL,       -- per-side auto-increment, computed client-side
  weight_kg        NUMERIC,
  logged_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.bales_bag_changes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "bales_bag_changes read" ON public.bales_bag_changes
  FOR SELECT USING (true);

CREATE POLICY "bales_bag_changes insert" ON public.bales_bag_changes
  FOR INSERT TO authenticated WITH CHECK (true);

-- No UPDATE policy -- immutable. No DELETE policy -- cleared only via
-- reset_bales_shift_log (SECURITY DEFINER), same as bales_live_log.

ALTER PUBLICATION supabase_realtime ADD TABLE public.bales_bag_changes;
