-- banbury_live_log: one row per logged chemical/tank checklist entry within
-- the current Banbury shift, mirroring live_log/bales_live_log's role for
-- Press/Bales. A Banbury "cycle" is a chemical/tank check cycle: the
-- operator taps to open one, works the six material/chemical ticks and both
-- tank levels, then logs it -- so a row spans start_time (the tap) to
-- check_time (the log), with run_time_minutes the interval between them, and
-- carries no per-entry output at all (see banbury_shift_config.sql for where
-- the shift's output totals live).
-- start_time/run_time_minutes were added later, hence the separate
-- banbury_live_log_add_start_time.sql for tables already created.
--
-- The six BOOLEAN columns default to true because the paper form's checks
-- are overwhelmingly all-ticked on every row -- components/BanburyForm.tsx
-- pre-checks all six so the operator only has to un-tick what wasn't done.
--
-- right_tank_level/left_tank_level are TEXT, not NUMERIC, because the paper
-- form records either a number (e.g. "302") or the word "Full" in the same
-- cell.
--
-- Not applied via a migration tool -- run this manually in the Supabase SQL
-- editor (same convention as bales_live_log.sql).

CREATE TABLE IF NOT EXISTS public.banbury_live_log (
  banbury_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id            INTEGER NOT NULL DEFAULT 1,
  check_number        INTEGER NOT NULL,
  start_time          TIMESTAMPTZ,    -- cycle opened (TAP TO START)
  check_time          TIMESTAMPTZ,    -- cycle logged (the check itself)
  run_time_minutes    INTEGER,        -- check_time - start_time, minutes
  crumb_rubber        BOOLEAN DEFAULT true,
  other_rubbers       BOOLEAN DEFAULT true,
  powdered_chemicals  BOOLEAN DEFAULT true,
  rpo                 BOOLEAN DEFAULT true,
  sulphur             BOOLEAN DEFAULT true,
  liquid_chemicals    BOOLEAN DEFAULT true,
  right_tank_level    TEXT,           -- numeric string or "Full"
  left_tank_level     TEXT,
  notes               TEXT,
  updated_at          TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.banbury_live_log ENABLE ROW LEVEL SECURITY;

-- Anyone (incl. the boss, not logged in) can READ the live checklist grid.
CREATE POLICY "banbury_live_log read" ON public.banbury_live_log
  FOR SELECT USING (true);

-- Only logged-in operators can WRITE.
CREATE POLICY "banbury_live_log insert" ON public.banbury_live_log
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "banbury_live_log update" ON public.banbury_live_log
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Deliberately NO DELETE policy -- same footgun/design as live_log/
-- bales_live_log (see reset_shift_log.txt's comment). Clearing only happens
-- through the SECURITY DEFINER reset_banbury_shift_log RPC
-- (reset_banbury_shift_log.txt).

ALTER PUBLICATION supabase_realtime ADD TABLE public.banbury_live_log;
