-- banbury_production_logs: one row per Banbury shift per day, written LIVE
-- as the shift runs by components/BanburyForm.tsx (insert on first checklist
-- entry logged, update on every entry after), mirroring production_logs /
-- bales_production_logs for Press/Bales.
--
-- product/bag_weight_kg/batches_made/mesh_bags_count/run_time_minutes are
-- snapshotted from banbury_shift_config at write time (same principle as
-- live_log.run_time_minutes, see live_log_add_run_time.sql) so a later
-- change to the shift's live totals doesn't retroactively alter a day
-- that's already archived. tonnes/average_output_ph are likewise
-- snapshotted, computed client-side from the sheet's own formulas
-- (Tonnes = Bags * Bag Weight / 1000, Average Output P/H = Tonnes / Run
-- Time), not recomputed from `checks` -- the checklist entries carry no
-- output data at all (see banbury_live_log.sql).
--
-- Unlike production_logs_dedupe.sql, this table starts empty, so the unique
-- index is created directly -- no separate inspect/cleanup pass is needed
-- (same as bales_production_logs.sql).
--
-- Not applied via a migration tool -- run this manually in the Supabase SQL
-- editor (same convention as bales_production_logs.sql).

CREATE TABLE IF NOT EXISTS public.banbury_production_logs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date               TEXT NOT NULL,          -- YYYY-MM-DD, Perth
  operator_shift     TEXT,                   -- "${operator} (${shift})"
  product            TEXT,
  bag_weight_kg      NUMERIC,
  batches_made       INTEGER,
  mesh_bags_count    INTEGER,
  tonnes             NUMERIC,                -- snapshotted, = bags * bag_weight_kg / 1000
  run_time_minutes   INTEGER,
  average_output_ph  NUMERIC,                -- snapshotted, = tonnes / (run_time_minutes/60)
  checks             JSONB DEFAULT '[]'::jsonb,
  updated_at         TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.banbury_production_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "banbury_production_logs read" ON public.banbury_production_logs
  FOR SELECT USING (true);

CREATE POLICY "banbury_production_logs insert" ON public.banbury_production_logs
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "banbury_production_logs update" ON public.banbury_production_logs
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- One row per (date, shift group), matching production_logs_one_per_shift_day
-- / bales_production_logs_one_per_shift_day. Both lower() and position() are
-- IMMUTABLE, so this expression is indexable.
--
-- components/BanburyForm.tsx must handle the resulting unique violation
-- (SQLSTATE 23505) exactly like PressForm.tsx/BalesForm.tsx: re-resolve the
-- shift's row and update it instead of erroring.
CREATE UNIQUE INDEX IF NOT EXISTS banbury_production_logs_one_per_shift_day
  ON public.banbury_production_logs (
    date,
    (position('night' in lower(operator_shift)) > 0)
  );
