-- Two-way chat between anonymous viewers and the logged-in operator.
-- Anyone (anon or authenticated) can read and send messages; there is no
-- UPDATE/DELETE policy since messages are immutable from the client.
-- Clearing happens entirely through the SECURITY DEFINER reset_shift_log RPC
-- (see reset_shift_log.txt), which bypasses RLS the same way it already does
-- for live_log.
CREATE TABLE shift_messages (
  id bigint generated by default as identity primary key,
  shift_id integer not null default 1,
  sender_name text not null,
  is_operator boolean not null default false,
  body text not null,
  created_at timestamptz not null default now()
);

ALTER TABLE shift_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read shift messages" ON shift_messages
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Public can send shift messages" ON shift_messages
  FOR INSERT TO anon, authenticated WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE shift_messages;
